services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    image: jenkins
    ports:
      - 31940:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
    external: true